app          = "cdrxiv-file-uploader"
kill_signal  = "SIGINT"
kill_timeout = 5

primary_region = "dfw"

[build]
    builder = "heroku/builder:24"
    buildpacks = [
        "heroku/buildpack-nodejs:3.3.3",
        "heroku/buildpack-python:0.19.1",
    ]

[[vm]]
    memory = "2048mb"
    size   = "shared-cpu-4x"

[env]
    JANEWAY_URL = 'https://janeway.cdrxiv.org'
    PORT        = "8000"
    TMPDIR      = "/data"
    ZENODO_URL  = "https://zenodo.org"

[mounts]
    destination = "/data"
    source      = "cdrxiv_file_uploader"

[processes]
    app = "gunicorn -w 2 -k uvicorn.workers.UvicornWorker -t 1800 src.main:app"

[[services]]
    auto_start_machines  = true
    auto_stop_machines   = true
    force_https          = true
    internal_port        = 8000
    min_machines_running = 1
    processes            = ["app"]
    protocol             = "tcp"

[[services.ports]]
    handlers = ["http"]
    port     = 80

[[services.ports]]
    handlers = ["http", "tls"]
    port     = 443
[services.concurrency]
    type = "connections"

[[services.tcp_checks]]
    grace_period  = "5s"
    interval      = "15s"
    restart_limit = 0
    timeout       = "3s"

[[services.http_checks]]
    grace_period = "30s"
    interval     = "1m"
    path         = "/health"
    timeout      = "15s"
