service: cdrxiv-file-uploader-lambda
useDotenv: true

provider:
  name: aws
  runtime: python3.10
  memorySize: 4096
  stage: ${opt:stage, 'dev'}
  region: ${opt:region, 'us-west-2'}

functions:
  app:
    handler: src/main.handler

    layers:
      - Ref: PythonRequirementsLambdaLayer
    url:
      cors: true
    events:
      - http:
          method: ANY
          path: /

      # - http:
      #     method: ANY
      #     path: /{proxy+}
    environment:
      ZENODO_ACCESS_TOKEN: ${env:ZENODO_ACCESS_TOKEN}
      ZENODO_URL: ${env:ZENODO_URL}

plugins:
  - serverless-dotenv-plugin
  - serverless-python-requirements

custom:
  pythonRequirements:
    layer: true
    dockerizePip: true
    zip: true
    slim: true
    slimPatterns:
      - '**/*.egg-info*'
    strip: false
    useStaticCache: true
    invalidateCaches: true
    useDownloadCache: true
    dockerImage: public.ecr.aws/lambda/python:3.10
    dockerRunCmdExtraArgs: ['--platform', 'linux/amd64']
    noDeploy:
      - pytest
      - boto3
      - botocore

package:
  patterns:
    - 'src/**'
    - '!**/*.pyc'
    - '!**/__pycache__'
    - '!.pytest_cache/**'
    - '!.venv/**'
    - '!node_modules/**'
    - '!tests/**'
    - '!aws-lambda/**'
